### Login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testing123"
}

> {% client.global.set("auth_token", response.body.token); %}


### Create
POST {{host}}/api/v1/jobs
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "company": "Test Company",
  "position": "Test position",
  "status": "pending",
  "jobType": "full-time",
  "jobLocation": "Palm Beach"
}

### List
# limit
# page
GET {{host}}/api/v1/jobs?limit=2&page=1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Search
# status=pending | decliend | interview
# jobType=full-time | part-time | internship
# search=dev
# sort=latest | oldest | a-z | z-a
GET {{host}}/api/v1/jobs?jobType=full-time&search=&sort=latest
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update
PATCH {{host}}/api/v1/jobs/62b8b5944aa1c206864588ae
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "company": "Facebook",
  "position": "Test position1"
}

### Delete
DELETE {{host}}/api/v1/jobs/62b8b5944aa1c206864588ae
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Stats
GET {{host}}/api/v1/jobs/stats
Content-Type: application/json
Authorization: Bearer {{auth_token}}